run:
  java -Xmx2G -Xms2G -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1HeapRegionSize=8M -XX:G1HeapWastePercent=5 -XX:G1MaxNewSizePercent=40 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1NewSizePercent=30 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -XX:MaxGCPauseMillis=200 -XX:MaxTenuringThreshold=1 -XX:SurvivorRatio=32 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar paperclip.jar --nogui

download:
  wget -O plugins/ProtocolLib.jar https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/build/libs/ProtocolLib.jar
  wget -O plugins/EssentialsX.jar https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsX-2.21.0-dev+93-3a6fdd9.jar
  #  curl -L -o plugins/LuckPerms.jar https://www.spigotmc.org/resources/luckperms.28140/download?version=544174
  #  curl -L -o plugins/Vault.jar https://www.spigotmc.org/resources/vault.34315/download?version=344916
  #  curl -L -o plugins/WorldEdit.jar https://dev.bukkit.org/projects/worldedit/files/latest
  # java -Dmaven.multiModuleProjectDirectory= -Djansi.passthrough=true -Dmaven.home=/snap/intellij-idea-community/508/plugins/maven/lib/maven3 -Dclassworlds.conf=/snap/intellij-idea-community/508/plugins/maven/lib/maven3/bin/m2.conf -Dmaven.ext.class.path=/snap/intellij-idea-community/508/plugins/maven/lib/maven-event-listener.jar -javaagent:/snap/intellij-idea-community/508/lib/idea_rt.jar=46285:/snap/intellij-idea-community/508/bin -Dfile.encoding=UTF-8 -classpath /snap/intellij-idea-community/508/plugins/maven/lib/maven3/boot/plexus-classworlds-2.7.0.jar:/snap/intellij-idea-community/508/plugins/maven/lib/maven3/boot/plexus-classworlds.license org.codehaus.classworlds.Launcher -Didea.version=2024.1.3 clean install
